theme: jekyll-theme-minimal
title: Maria Y. Rodriguez MSW, PhD's homepage
description: A static page for research updates!
social_links:
  - name: Google Scholar
    url: https://scholar.google.com/citations?user=EqsjbTQAAAAJ&hl=en
  - name: LinkedIn
    url: www.linkedin.com/in/rodriguezmariay
logo: /assets/img/my_image.png
